//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_ProjectMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_user()
        {
            this.Tbl_invoice = new HashSet<Tbl_invoice>();
        }
        [Key]
        public int U_id { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Name Required")]

        public string U_name { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Contact No Required")]

        public string U_contact { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Password Required")]
        [DataType(DataType.Password)]
        public string U_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_invoice> Tbl_invoice { get; set; }
    }
}
