//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_ProjectMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_product()
        {
            this.Tbl_order = new HashSet<Tbl_order>();
        }
        [Key]
        public int Pro_id { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Name Required")]
        public string Pro_name { get; set; }
       
       
        public int Pro_price { get; set; }
        [StringLength(150)]
        [Required(ErrorMessage = "Desription Required")]
        public string Pro_des { get; set; }
        public string Pro_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_order> Tbl_order { get; set; }
    }
}
